# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
