# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_auto_20170307_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood.Blood'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.District'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
