# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
