# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrc', '0005_rrc_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrc',
            name='group',
            field=models.ForeignKey(default='RRC', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
