# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_auto_20170322_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='rrc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrc.Rrc'),
        ),
    ]
