# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrc', '0006_auto_20170307_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rrc',
            name='group',
        ),
    ]
