# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrc', '0007_remove_rrc_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rrc',
            name='user',
        ),
    ]
