# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0010_auto_20170307_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(default='one', max_length=15),
        ),
    ]
