# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20170213_0924'),
        ('request', '0002_auto_20170220_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.District'),
        ),
    ]
